/* KEREK Autopilot 1.0 — client-side beta, no payment, no automatic orders. */
(()=>{'use strict';
const KEY='kerek_autopilot_v1',APP=()=>window.KerekApp,fmt=n=>new Intl.NumberFormat('ru-RU').format(Math.round(n||0))+' ₸';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let settings={monthly:100000,weekly:20000,household:2,enabled:true};try{settings={...settings,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(_){}
function store(){try{localStorage.setItem(KEY,JSON.stringify(settings))}catch(_){}}
function products(){return APP()?.data?.products||[]}
function state(){return APP()?.state}
function orders(){return (state()?.orders||[]).filter(o=>!o.legacy&&o.quote&&Number.isFinite(Number(o.quote.total)))}
function spend(){const now=new Date(),month=now.getMonth(),year=now.getFullYear();return orders().filter(o=>{const d=new Date(o.createdAt||o.created_at);return d.getMonth()===month&&d.getFullYear()===year&&!['cancelled','canceled'].includes(o.status)}).reduce((a,o)=>a+Number(o.quote.total||0),0)}
function recommend(){const ps=products().filter(p=>p.active!==false&&Number(p.stock)>0),history={};orders().forEach(o=>(o.items||[]).forEach(x=>{if(x.id)history[String(x.id)]=(history[String(x.id)]||0)+Math.max(1,Number(x.qty)||1)}));
const favourites=new Set((state()?.favorites||[]).map(String));let candidates=ps.map(p=>({...p,score:(history[String(p.id)]||0)*8+(favourites.has(String(p.id))?5:0)+(Number(p.popularity)||0)/100}));if(Object.keys(history).length)candidates.sort((a,b)=>b.score-a.score);else candidates.sort((a,b)=>Number(b.popularity||0)-Number(a.popularity||0));
const pantry=new Set((state()?.pantry||[]).filter(x=>x.confirmed&&Number(x.amount)>0).map(x=>x.ingredient));candidates=candidates.filter(p=>!pantry.has(p.ingredient));const budget=Math.max(0,Math.min(settings.weekly,settings.monthly-spend()));let sum=0,items=[];for(const p of candidates){if(items.length>=Math.max(5,Math.min(16,settings.household*4+4)))break;if(sum+Number(p.price)>budget)continue;items.push(p);sum+=Number(p.price)}return {items,sum,budget};}
function markup(){const s=state();if(!s)return '';const spent=spend(),left=Math.max(0,settings.monthly-spent),pct=Math.min(100,Math.round(spent/settings.monthly*100)),r=recommend(),kk=s.language==='kk';const tr=(ru,kz)=>kk?kz:ru;
return `<section class="ka-panel" id="kerek-autopilot" aria-label="KEREK Autopilot"><div class="ka-heading"><div><span class="ka-eyebrow">✦ KEREK AUTOPILOT · BETA</span><h2>${tr('Ваши покупки под контролем','Сатып алуыңыз бақылауда')}</h2><p>${tr('Готовая корзина и семейный бюджет. Без автоматических списаний.','Дайын себет және отбасылық бюджет. Автоматты төлемсіз.')}</p></div><span class="ka-bubble">↻</span></div><div class="ka-layout"><div class="ka-budget"><div class="ka-mini">${tr('Осталось на этот месяц','Осы айға қалды')}</div><strong>${fmt(left)}</strong><div class="ka-muted">${tr('Потрачено в тестовых заказах','Сынақ тапсырыстарына жұмсалды')}: ${fmt(spent)} / ${fmt(settings.monthly)}</div><div class="ka-track"><span style="width:${pct}%"></span></div><label class="ka-field">${tr('Месячный бюджет, ₸','Айлық бюджет, ₸')}<input data-ka-field="monthly" type="number" min="1000" max="10000000" step="1000" value="${settings.monthly}"></label></div><div class="ka-basket"><div class="ka-mini">${tr('Предложение на неделю','Апталық ұсыныс')}</div><strong>${r.items.length} ${tr('товаров','тауар')} · ${fmt(r.sum)}</strong><p>${r.items.length?r.items.slice(0,5).map(p=>escape(kk?(p.name_kk||p.name):p.name)).join(' · '):tr('Пока нет подходящих товаров в пределах бюджета','Бюджетке сай тауар табылмады')}</p><div class="ka-fields"><label class="ka-field">${tr('Бюджет недели, ₸','Апталық бюджет, ₸')}<input data-ka-field="weekly" type="number" min="500" max="1000000" step="500" value="${settings.weekly}"></label><label class="ka-field">${tr('Человек','Адам')}<input data-ka-field="household" type="number" min="1" max="12" value="${settings.household}"></label></div><button class="ka-button" data-ka-action="add" ${r.items.length?'':'disabled'}>${tr('Добавить подборку в корзину →','Тауарларды себетке қосу →')}</button><p class="ka-muted">${tr('Подбор на основе истории и популярности. Наличие и цены демонстрационные; доставка считается в корзине.','Таңдау тарих пен танымалдыққа негізделген. Бағалар мен қалдықтар сынақтық.')}</p></div></div><div class="ka-bottom"><span>🍳 ${tr('Не знаете, что приготовить?','Не пісіруді білмейсіз бе?')}</span><button data-ka-action="recipes">${tr('Выбрать ужин →','Кешкі асты таңдау →')}</button></div></section>`}
function mount(){const app=document.getElementById('app');if(!app||document.getElementById('kerek-autopilot'))return;const hero=app.querySelector('.hero'),main=app.querySelector('main');if(!hero||!main)return;hero.insertAdjacentHTML('afterend',markup());}
let pending=false;const obs=new MutationObserver(()=>{if(pending)return;pending=true;queueMicrotask(()=>{pending=false;mount()})});const root=document.getElementById('app');if(root){obs.observe(root,{childList:true,subtree:true});mount()}
document.addEventListener('change',ev=>{const key=ev.target?.dataset?.kaField;if(!key)return;const bounds={monthly:[1000,10000000],weekly:[500,1000000],household:[1,12]},[min,max]=bounds[key];const n=Number(ev.target.value);if(!Number.isFinite(n)||n<min||n>max){ev.target.value=settings[key];return}settings[key]=Math.floor(n);store();document.getElementById('kerek-autopilot')?.remove();mount()});
document.addEventListener('click',ev=>{const b=ev.target.closest('[data-ka-action]');if(!b)return;const a=b.dataset.kaAction;if(a==='recipes'){APP()?.navigate('recipes');return}if(a!=='add')return;const app=APP(),s=state(),r=recommend();if(!s||!r.items.length)return;const merged={...s.cart};for(const p of r.items){const id=String(p.id);if((merged[id]||0)+1>Math.min(99,Number(p.stock)))continue;merged[id]=(merged[id]||0)+1}s.cart=merged;try{localStorage.setItem('kerek_v3',JSON.stringify(s))}catch(_){}app.render();app.navigate('cart');});
})();
