const test=require('node:test');
const assert=require('node:assert/strict');
const C=require('../public/js/core.js');
const D=require('../server/seed.json');
const {products:P,recipes:R,settings:T}=D;
const run=(name,fn)=>test(name,fn);
run('retains original SKU IDs and seed is marked demonstration',()=>{assert.equal(P.length,32);assert(P.every(p=>p.demo));assert.equal(P.find(p=>p.id==='0').ingredient,'milk');});
run('search finds Russian and Kazakh product names',()=>{assert(C.search(P,'молоко').items.length>=2);assert(C.search(P,'сүт').items.length>=2);});
run('fuzzy search corrects one typo and returns no random results',()=>{assert(C.search(P,'молко').corrected);assert(C.search(P,'молко').items.some(p=>p.ingredient==='milk'));assert.equal(C.search(P,'абракадабрам').items.length,0);});
run('search matches multiple words and brand',()=>{const p=P[0];assert(C.search(P,'молоко '+p.brand).items.some(x=>x.id===p.id));});
run('normalization handles case punctuation and ё',()=>assert.equal(C.norm('  ЁЖ,  СҮТ! '),'еж сүт'));
run('bad persisted carts do not crash or accept negative quantities',()=>{assert.deepEqual(C.cleanCart(null,P),{});assert.deepEqual(C.cleanCart({'0':-1,unknown:1},P),{});assert.deepEqual(C.cleanCart([] ,P),{});});
run('cart quantity is limited to current stock',()=>{let p={...P[0],stock:2};assert.deepEqual(C.cleanCart({'0':4},[p]),{'0':2});});
run('empty cart never pays delivery',()=>{const q=C.quote({},P,T);assert.equal(q.total,0);assert.equal(q.delivery,0);});
run('all package prices plus delivery are included',()=>{const q=C.quote({'0':2,'1':1},P,T);assert.equal(q.subtotal,2270);assert.equal(q.total,3260);});
run('unknown product and out of stock are explicit errors',()=>{assert(C.quote({bogus:1},P,T).errors.length);assert(C.quote({'31':1},P,T).errors.some(e=>e.startsWith('stock:')));});
run('coupon cap and free delivery',()=>{const q=C.quote({'10':8},P,T,{promo:'KEREK10'});assert.equal(q.discount,2000);assert.equal(q.delivery,0);});
run('invalid and expired coupons do not discount',()=>{assert.equal(C.quote({'0':2},P,T,{promo:'NOPE'}).promoError,'promo_invalid');let t=C.clone(T);t.promos[0].endsAt='2000-01-01';assert.equal(C.quote({'0':2},P,t,{promo:'KEREK10'}).discount,0);});
run('redemption is constrained by balance and order percentage',()=>{let q=C.quote({'0':2},P,T,{bonus:99999,balance:99999});assert.equal(q.bonus,276);assert.equal(C.quote({'0':2},P,T,{bonus:500,balance:10}).bonus,10);});
run('unknown zone is blocked',()=>assert(C.quote({'0':2},P,T,{zone:'not-real'}).errors.includes('zone_unavailable')));
run('aggregate merges repeated ingredients and rounds to whole packs',()=>{let recipes=[{id:'a',ingredients:[{key:'rice',amount:100,unit:'g'}]},{id:'b',ingredients:[{key:'rice',amount:100,unit:'g'}]}];let p=[{...P[5],pack:500,stock:10}];const a=C.aggregate(['a','b'],2,recipes,p);assert.equal(a.details[0].required,400);assert.equal(a.details[0].qty,1);assert.equal(a.details[0].leftover,100);});
run('more people increase actual ingredient requirements',()=>{const a=C.aggregate(['plov'],2,R,P),b=C.aggregate(['plov'],4,R,P);assert.equal(b.details[0].required,a.details[0].required*2);});
run('confirmed unexpired pantry offsets requirements',()=>{const r=[{id:'r',ingredients:[{key:'rice',amount:100,unit:'g'}]}];let a=C.aggregate(['r'],2,r,P,[{ingredient:'rice',amount:200,unit:'g',confirmed:true}]);assert.deepEqual(a.cart,{});assert.equal(a.details[0].fromHome,200);});
run('expired unconfirmed or wrong unit pantry is excluded',()=>{const r=[{id:'r',ingredients:[{key:'rice',amount:100,unit:'g'}]}];for(const h of [{confirmed:false,unit:'g'},{confirmed:true,unit:'ml'},{confirmed:true,unit:'g',expiresAt:'2000-01-01'}])assert.equal(C.aggregate(['r'],2,r,P,[{ingredient:'rice',amount:1000,...h}]).details[0].fromHome,0);});
run('stock failure yields missing ingredient rather than imaginary product',()=>{const r=[{id:'r',ingredients:[{key:'not-in-catalogue',amount:100,unit:'g'}]}];assert.deepEqual(C.aggregate(['r'],2,r,P).missing,['not-in-catalogue']);});
run('cheapest choice considers full packages not just unit price',()=>{const r=[{id:'r',ingredients:[{key:'rice',amount:400,unit:'g'}]}];const ps=[{...P[5],id:'small',pack:500,price:600},{...P[5],id:'bulk',pack:1000,price:900}];assert.deepEqual(C.aggregate(['r'],1,r,ps).cart,{small:1});});
run('rule parser reads Russian family budget and number words',()=>{let o=C.parseRequest('Для семьи из четырех человек на неделю за 40 000 ₸');assert.equal(o.people,4);assert.equal(o.days,7);assert.equal(o.budget,40000);});
run('rule parser reads Kazakh budget and people',()=>{let o=C.parseRequest('Төрт адамға бес күнге 35 000 теңге, етсіз');assert.equal(o.people,4);assert.equal(o.days,5);assert.equal(o.budget,35000);assert(o.vegetarian);});
run('days in request must not accidentally become people',()=>{let o=C.parseRequest('Подбери завтраки на пять дней', {people:2});assert.equal(o.people,2);assert.equal(o.days,5);});
run('plov resets to one meal and sufficient cooking time',()=>{let o=C.parseRequest('Плов на шесть человек за 20 000 ₸');assert.equal(o.people,6);assert.equal(o.days,1);assert.equal(o.recipe,'plov');});
run('a new non-plov request does not retain previous recipe restriction',()=>{let o=C.parseRequest('завтраки на 3 дня',{recipe:'plov',people:2});assert.equal(o.recipe,undefined);assert.equal(o.meal,'breakfast');});
run('valid plan stays under full budget and honours portions',()=>{let p=C.makePlan({people:4,days:5,budget:25000,minutes:45},P,R,T);assert(!p.error);assert(p.quote.total<=25000);assert.equal(p.selected.length,5);assert.equal(p.options.people,4);});
run('vegetarian plans omit meat ingredients',()=>{let p=C.makePlan({people:2,days:5,budget:20000,vegetarian:true},P,R,T);assert(!p.error);assert(p.details.every(d=>!['chicken','beef','fish'].includes(d.ingredient)));});
run('excluded dairy is never selected',()=>{let p=C.makePlan({people:2,days:3,budget:20000,meal:'breakfast',exclude:['milk']},P,R,T);assert(p.error==='no_recipes'||p.details.every(d=>!['milk','cheese','butter','yogurt'].includes(d.ingredient)));});
run('infeasible budget does not invent a complete plan',()=>{let p=C.makePlan({people:8,days:7,budget:500},P,R,T);assert(p.error);assert.equal(p.selected.length,0);});
run('invalid planner inputs rejected',()=>{for(const people of [0,9,-1,1.5])assert.equal(C.makePlan({people},P,R,T).error,'invalid_plan');});
run('cheaper alternatives retain required physical quantity',()=>{let p=[{...P[5],id:'a',pack:800,price:1000},{...P[5],id:'b',pack:500,price:300}];let a=C.cheaper({a:2},p)[0];assert.equal(a.qty,4);assert.equal(a.saving,800);});
run('cheaper alternatives do not silently reduce quantity when stock insufficient',()=>{let p=[{...P[5],id:'a',pack:800,price:1000},{...P[5],id:'b',pack:500,price:300,stock:3}];assert.equal(C.cheaper({a:2},p).length,0);});
