"""Integration contracts. No invented Kaspi, SMS or courier API endpoints.
Implement against the chosen provider's official contract; validate webhooks and
make money movements idempotent before enabling live mode.
"""
from typing import Protocol
class SmsProvider(Protocol):
 def send_code(self,phone:str,code:str,request_id:str)->None:...
class PaymentProvider(Protocol):
 def create_payment(self,order_id:str,amount:int,currency:str,idempotency_key:str)->dict:...
 def verify_webhook(self,raw_body:bytes,headers:dict)->dict:...
 def refund(self,payment_id:str,amount:int,idempotency_key:str)->dict:...
class CourierProvider(Protocol):
 def create_delivery(self,order:dict,idempotency_key:str)->dict:...
 def tracking(self,delivery_id:str)->dict:...
class PushProvider(Protocol):
 def notify(self,subscription:dict,title:str,body:str)->None:...
CAPABILITIES={'sms':False,'payments':False,'kaspi':False,'courierMap':False,'push':False,'llm':False}
